export enum ActionName {
  UPDATE_CURRENCIES = 'UPDATE_CURRENCIES',
  SELECT_CRYPTOCURRENCY = 'SELECT_CRYPTOCURRENCY',
  SELECT_FIAT_CURRENCY = 'SELECT_FIAT_CURRENCY',
  UPDATE_FIAT_CURRENCY = 'UPDATE_FIAT_CURRENCY',
}
